#!/usr/bin/env bash

if [[ $# -ne 2 ]] ; then
    >&2 echo -e "Usage: $0 <action> <sourcecode-file>\nPrank Example: $0 prank controller.js\nFix Example: $0 fix controller.js"
    exit 1
fi

## Case in-sensitive comparison
shopt -s nocasematch

## Validates the input
validate_input () {

    if [[ "$1" != "prank" ]] && [[ "$1" != "fix" ]] ; then
        >&2 echo -e "Invalid action \"$1\". Allowed actions are \"prank\" and \"fix\""
        exit 1
    fi

    if [[ ! -f "$2" ]] ; then    
        >&2 echo -e "File \"$2\" not found"
        exit 1
    fi
}


ACTION=$1
FILE=$2

SPACE_CHAR=' '
INVISIBLE_CHAR='‌‌ '


validate_input $ACTION $FILE

if [[ $ACTION = "prank" ]] ; then
    sed -i -e "s/$SPACE_CHAR/$INVISIBLE_CHAR/g" $FILE
elif [[ $ACTION = "fix" ]]; then
    sed -i -e "s/$INVISIBLE_CHAR/$SPACE_CHAR/g" $FILE
fi


